//    Chromis POS  - The New Face of Open Source POS
//    Copyright (c) (c) 2015-2016
//    http://www.chromis.co.uk
//
//    This file is part of Chromis POS
//
//     Chromis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Chromis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Chromis POS.  If not, see <http://www.gnu.org/licenses/>.

package uk.chromis.pos.inventory;

import java.awt.Component;
import java.util.UUID;
import java.util.Date;
import uk.chromis.basic.BasicException;
import uk.chromis.beans.JCalendarDialog;
import uk.chromis.data.gui.ComboBoxValModel;
import uk.chromis.data.loader.SentenceList;
import uk.chromis.data.user.DirtyManager;
import uk.chromis.data.user.EditorRecord;
import uk.chromis.format.Formats;
import uk.chromis.pos.forms.AppLocal;
import uk.chromis.pos.forms.DataLogicSales;

/**
 *
 * @author adrian
 */
public class BoxOfficeProductSetsEditor extends javax.swing.JPanel implements EditorRecord {
    
    private Object boxofficeproductsetid;
    

    private enum RecordStatus {
        EOF,
        UPDATE,
        INSERT,
        DELETE
    }

    private BoxOfficeProductSetsFilter boxOfficeProductSetFilter;

    private RecordStatus recStatus;
    
    
    /** Creates new form AttributesValuesEditor
    * @param dlSales
     * @param dirty
     * @throws uk.chromis.basic.BasicException */
    public BoxOfficeProductSetsEditor(DataLogicSales dlSales, DirtyManager dirty, BoxOfficeProductSetsFilter filter) throws BasicException {
        
        initComponents();

        this.boxOfficeProductSetFilter = filter;
        
        m_jName.getDocument().addDocumentListener(dirty);
        m_jActive.addActionListener(dirty);

    }
    
    
    /**
     *
     * @param insertid
     */
    public void setInsertId(String insertid) {

        this.boxofficeproductsetid = insertid;
    }

    /**
     *
     */
    @Override
    public void refresh() {
    }


    public void activate() throws BasicException {

    }


    /**
     *
     */
    @Override
    public void writeValueEOF() {

        boxofficeproductsetid = null;
        m_jName.setText(null);
        m_jActive.setSelected(false);

        m_jName.setEnabled(false);
        m_jActive.setEnabled(false);

        this.recStatus = RecordStatus.EOF;
        
    }

    /**
     *
     */
    @Override
    public void writeValueInsert() {

        boxofficeproductsetid = UUID.randomUUID().toString();

        m_jName.setText(null);
        m_jActive.setSelected(true);

        m_jName.setEnabled(true);
        m_jActive.setEnabled(true);

        this.recStatus = RecordStatus.INSERT;
    }

    /**
     *
     * @param value
     */
    @Override
    public void writeValueEdit(Object value) {

        Object[] obj = (Object[]) value;

        boxofficeproductsetid = obj[0];
        
        m_jName.setText(Formats.STRING.formatValue(obj[1]));
        m_jActive.setSelected((Boolean) obj[2]);

        m_jName.setEnabled(true);
        m_jActive.setEnabled(true);

        this.recStatus = RecordStatus.UPDATE;

    }

    /**
     *
     * @param value
     */
    @Override
    public void writeValueDelete(Object value) {

        Object[] obj = (Object[]) value;

        boxofficeproductsetid = obj[0];
        m_jName.setText(Formats.STRING.formatValue(obj[1]));
        m_jActive.setSelected((Boolean) obj[2]);

        m_jName.setEnabled(false);
        m_jActive.setEnabled(false);
        
        this.recStatus = RecordStatus.DELETE;

    }

    
    /**
     *
     * @return
     */
    @Override
    public Component getComponent() {
        return this;
    }

    /**
     *
     * @return
     * @throws BasicException
     */
    @Override
    public Object createValue() throws BasicException {
        return new Object[] {
            boxofficeproductsetid,
            m_jName.getText(),
            m_jActive.isSelected()
        };
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        m_jActive = new eu.hansolo.custom.SteelCheckBox();

        jLabel13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel13.setText(AppLocal.getIntString("label.boxofficeproductsetsname")); // NOI18N

        m_jName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel15.setText(AppLocal.getIntString("label.boxofficeproductsetsactive")); // NOI18N

        m_jActive.setText(" ");
        m_jActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jActiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_jName))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(m_jActive, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 217, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_jName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(m_jActive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 209, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void m_jActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jActiveActionPerformed

    }//GEN-LAST:event_m_jActiveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private eu.hansolo.custom.SteelCheckBox m_jActive;
    private javax.swing.JTextField m_jName;
    // End of variables declaration//GEN-END:variables


}
