//    Chromis POS  - The New Face of Open Source POS
//    Copyright (c) (c) 2015-2016
//    http://www.chromis.co.uk
//
//    This file is part of Chromis POS
//
//     Chromis POS is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.
//
//    Chromis POS is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.
//
//    You should have received a copy of the GNU General Public License
//    along with Chromis POS.  If not, see <http://www.gnu.org/licenses/>.
//
package uk.chromis.pos.inventory;

import java.awt.Component;
import java.util.UUID;
import javax.swing.JPanel;
import uk.chromis.basic.BasicException;
import uk.chromis.data.user.DirtyManager;
import uk.chromis.data.user.EditorRecord;
import uk.chromis.format.Formats;
import uk.chromis.pos.forms.AppLocal;

/**
 *
 * @author adrianromero
 */
public final class RatingsEditor extends JPanel implements EditorRecord {

    private Object m_id;

    /**
     * Creates new form JEditProduct
     *
     * @param dirty
     */
    public RatingsEditor(DirtyManager dirty) {
        
        initComponents();

        m_jName.getDocument().addDocumentListener(dirty);
        m_jActive.addActionListener(dirty);
		
        writeValueEOF();
    }

    /**
     *
     * @throws BasicException
     */
    public void activate() throws BasicException {

    }

    public String getID() {
        return (String) m_id;
    }

    // Save the currently edited show.  
    public void saveProduct() {
    }

    /**
     *
     */
    @Override
    public void refresh() {
    }

    /**
     *
     */
    @Override
    public void writeValueEOF() {

        m_jTitle.setText(AppLocal.getIntString("label.recordeof"));
        m_id = null;
        m_jName.setText(null);
        m_jActive.setSelected(false);

        m_jName.setEnabled(false);
        m_jActive.setEnabled(false);
    }

    /**
     *
     */
    @Override
    public void writeValueInsert() {
        
        m_jTitle.setText(AppLocal.getIntString("label.recordnew"));
        m_id = UUID.randomUUID().toString();
        m_jName.setText(null);
        m_jActive.setSelected(true);

        // Los habilitados
        m_jName.setEnabled(true);
        m_jActive.setEnabled(true);

    }


    /**
     *
     * @param value
     */
    @Override
    public void writeValueDelete(Object value) {

        m_jTitle.setText(AppLocal.getIntString("label.recorddeleted"));
        
        m_jTitle.setText(AppLocal.getIntString("label.recordnew"));
        m_id = UUID.randomUUID().toString();
        m_jName.setText(null);
        m_jActive.setSelected(false);

        m_jName.setEnabled(false);
        m_jActive.setEnabled(false);
        
    }

    /**
     *
     * @param value
     */
    @Override
    public void writeValueEdit(Object value) {

        Object[] myrating = (Object[]) value;
        
        m_id = myrating[0];
        m_jName.setText(Formats.STRING.formatValue(myrating[1]));
        m_jActive.setSelected((Boolean) myrating[2]);
        
        m_jName.setEnabled(true);
        m_jActive.setEnabled(true);
        
    }

    /**
     *
     * @return myrating
     * @throws BasicException
     */
    @Override
    public Object createValue() throws BasicException {
        
        Object[] myrating = new Object[3];
        myrating[0] = m_id;
        myrating[1] = m_jName.getText();
        myrating[2] = m_jActive.isSelected();
        
        return myrating;

    }

    /**
     *
     * @return this
     */
    @Override
    public Component getComponent() {
        return this;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jScheduleMode = new javax.swing.ButtonGroup();
        m_jTitle = new javax.swing.JLabel();
        m_jName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        m_jActive = new eu.hansolo.custom.SteelCheckBox();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        m_jTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        m_jTitle.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        add(m_jTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 0, 330, 30));

        m_jName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        m_jName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                m_jNameFocusLost(evt);
            }
        });
        add(m_jName, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 270, 25));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel4.setText(AppLocal.getIntString("label.showname")); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText(AppLocal.getIntString("label.showactive")); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        m_jActive.setText(" ");
        m_jActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jActiveActionPerformed(evt);
            }
        });
        add(m_jActive, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 30, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void m_jActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jActiveActionPerformed
    }//GEN-LAST:event_m_jActiveActionPerformed

    private void m_jNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_m_jNameFocusLost
    }//GEN-LAST:event_m_jNameFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private eu.hansolo.custom.SteelCheckBox m_jActive;
    private javax.swing.JTextField m_jName;
    private javax.swing.ButtonGroup m_jScheduleMode;
    private javax.swing.JLabel m_jTitle;
    // End of variables declaration//GEN-END:variables

}
