/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.chromis.pos.catalog;


import java.awt.Component;
import java.awt.Dialog;
import java.awt.Frame;
import java.awt.Window;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import javax.swing.SwingUtilities;
import uk.chromis.pos.forms.DataLogicSales;
import uk.chromis.pos.ticket.ShowSalesInfo;

/**
 *
 * @author nick
 */
public class JBoxOfficeDialog extends javax.swing.JDialog  {
  
    private DataLogicSales m_dlSales;
    private ShowSalesInfo m_selectedShow;
    
    
    /**
     * Creates new form jCatalogBoxOfficeDialog
     */
    public JBoxOfficeDialog(java.awt.Frame parent, boolean modal, DataLogicSales dlSales) {
        super(parent, modal);
        m_dlSales = dlSales;
        initComponents();
    }

    public JBoxOfficeDialog(java.awt.Dialog parent, boolean modal, DataLogicSales dlSales) {
        super(parent, modal);
        m_dlSales = dlSales;
        initComponents();
    }
    
    
    public static ShowSalesInfo showDialog(Component parent, DataLogicSales dlSales) {
        
        Window window = SwingUtilities.windowForComponent(parent);
        
        JBoxOfficeDialog myMsg;
        if (window instanceof Frame) { 
            myMsg = new JBoxOfficeDialog((Frame) window, true, dlSales);
        } else {
            myMsg = new JBoxOfficeDialog((Dialog) window, true, dlSales);
        }
        
        
        myMsg.jCatalogBoxOfficePanel1.addPropertyChangeListener("Show", new JPanelShowChange(myMsg));
        
        myMsg.setVisible(true);
        
        return myMsg.m_selectedShow;
        
    }
    
    
    private static class JPanelShowChange implements PropertyChangeListener {
        private final JBoxOfficeDialog me;
        public JPanelShowChange(JBoxOfficeDialog p) {
            me = p;
        }
        @Override
        public void propertyChange(PropertyChangeEvent evt) {
            me.m_selectedShow = me.jCatalogBoxOfficePanel1.getSelectedShow();
            me.setVisible(false);
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBoxOfficePanel = new javax.swing.JPanel();
        jCatalogBoxOfficePanel1 = new uk.chromis.pos.catalog.JBoxOfficePanel(m_dlSales);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jBoxOfficePanelLayout = new javax.swing.GroupLayout(jBoxOfficePanel);
        jBoxOfficePanel.setLayout(jBoxOfficePanelLayout);
        jBoxOfficePanelLayout.setHorizontalGroup(
            jBoxOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoxOfficePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCatalogBoxOfficePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
                .addContainerGap())
        );
        jBoxOfficePanelLayout.setVerticalGroup(
            jBoxOfficePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoxOfficePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jCatalogBoxOfficePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 843, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jBoxOfficePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jBoxOfficePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBoxOfficePanel;
    private uk.chromis.pos.catalog.JBoxOfficePanel jCatalogBoxOfficePanel1;
    // End of variables declaration//GEN-END:variables
}
