/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uk.chromis.pos.catalog;

import java.awt.Component;
import java.awt.event.ActionListener;
import java.util.Date;
import javax.swing.*;
import javax.swing.event.*;
import uk.chromis.basic.BasicException;
import uk.chromis.beans.JCalendarDialog;
import uk.chromis.format.Formats;


/**
 *
 * @author nick
 */
public class jCatalogBoxOffice extends JPanel implements ListSelectionListener, CatalogSelector {

    private Date selectedDate;
    
    
    /**
     * Creates new form jCatalogBoxOffice
     */
    public jCatalogBoxOffice() {
        
        selectedDate = new Date();
        
        initComponents();
        
    }
    
    
    @Override
    public void valueChanged(ListSelectionEvent evt) {
        
    }

    
    
    /**
     *
     * @throws BasicException
     */
    @Override
    public void loadCatalog() throws BasicException {
        
    }

    /**
     *
     * @param id
     */
    @Override
    public void showCatalogPanel(String id) {
        
    }

    /**
     *
     * @param value
     */
    @Override
    public void setComponentEnabled(boolean value) {
        
    }

    /**
     *
     * @return
     */
    @Override
    public Component getComponent() {
        return this;
    }
    
    /**
     *
     * @param l
     */
    @Override
    public void addActionListener(ActionListener l) {
        
    }

    /**
     *
     * @param l
     */
    @Override
    public void removeActionListener(ActionListener l) {
        
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        m_jPanelDateSelector = new javax.swing.JPanel();
        m_jButtonDate = new javax.swing.JButton();
        m_jButtonDatePrevious = new javax.swing.JButton();
        m_jButtonDateNext = new javax.swing.JButton();
        m_jPanelShows = new javax.swing.JPanel();

        m_jButtonDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        m_jButtonDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jButtonDateActionPerformed(evt);
            }
        });

        m_jButtonDatePrevious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/chromis/images/1leftarrow.png"))); // NOI18N
        m_jButtonDatePrevious.setFocusPainted(false);
        m_jButtonDatePrevious.setFocusable(false);
        m_jButtonDatePrevious.setMargin(new java.awt.Insets(8, 14, 8, 14));
        m_jButtonDatePrevious.setRequestFocusEnabled(false);
        m_jButtonDatePrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jButtonDatePreviousActionPerformed(evt);
            }
        });

        m_jButtonDateNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uk/chromis/images/1rightarrow.png"))); // NOI18N
        m_jButtonDateNext.setFocusPainted(false);
        m_jButtonDateNext.setFocusable(false);
        m_jButtonDateNext.setMargin(new java.awt.Insets(8, 14, 8, 14));
        m_jButtonDateNext.setRequestFocusEnabled(false);
        m_jButtonDateNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_jButtonDateNextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout m_jPanelDateSelectorLayout = new javax.swing.GroupLayout(m_jPanelDateSelector);
        m_jPanelDateSelector.setLayout(m_jPanelDateSelectorLayout);
        m_jPanelDateSelectorLayout.setHorizontalGroup(
            m_jPanelDateSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_jPanelDateSelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_jButtonDatePrevious)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_jButtonDate, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_jButtonDateNext))
        );
        m_jPanelDateSelectorLayout.setVerticalGroup(
            m_jPanelDateSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(m_jPanelDateSelectorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(m_jPanelDateSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(m_jButtonDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(m_jPanelDateSelectorLayout.createSequentialGroup()
                        .addGroup(m_jPanelDateSelectorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_jButtonDateNext)
                            .addComponent(m_jButtonDatePrevious))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout m_jPanelShowsLayout = new javax.swing.GroupLayout(m_jPanelShows);
        m_jPanelShows.setLayout(m_jPanelShowsLayout);
        m_jPanelShowsLayout.setHorizontalGroup(
            m_jPanelShowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        m_jPanelShowsLayout.setVerticalGroup(
            m_jPanelShowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 298, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(m_jPanelShows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(m_jPanelDateSelector, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(m_jPanelDateSelector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_jPanelShows, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void m_jButtonDatePreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jButtonDatePreviousActionPerformed

 

    }//GEN-LAST:event_m_jButtonDatePreviousActionPerformed

    private void m_jButtonDateNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jButtonDateNextActionPerformed


    }//GEN-LAST:event_m_jButtonDateNextActionPerformed

    private void m_jButtonDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_jButtonDateActionPerformed

        // Display the calendar dialog and set the selected date based on user action
        Date date = this.selectedDate;
        date = JCalendarDialog.showCalendar(this, date);
        if (date != null) {
            this.selectedDate = date;
        }
        
        
    }//GEN-LAST:event_m_jButtonDateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton m_jButtonDate;
    private javax.swing.JButton m_jButtonDateNext;
    private javax.swing.JButton m_jButtonDatePrevious;
    private javax.swing.JPanel m_jPanelDateSelector;
    private javax.swing.JPanel m_jPanelShows;
    // End of variables declaration//GEN-END:variables
}
